created get_customer. working on GLF-17
Scottsdale-Golf-Group/sgg_utils pull request #15
Opened 2024-03-22 17:04 UTC by doyouknolou

please review thank you!

2024-03-22 17:39 UTC, michaeldfutch requested changes
The function looks good with one small change about the delimiter. Can you also add a test?

2024-03-22 17:39 UTC, michaeldfutch commented on src/sgg_utils/foreup_utils.py
> +        included = '?include=' + '&'.join(include)
The join delimiter should be "," instead of "&". I made a change yesterday to a few of the other functions that still used &.

2024-03-22 22:04 UTC, doyouknolou reviewed
@michaeldfutch

2024-03-27 18:18 UTC, michaeldfutch reviewed
Looks good! Can you increment the version number in pyproject.toml?

2024-03-27 18:21 UTC, michaeldfutch approved these changes
🚀

2024-03-27 18:22 UTC, merged